module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    }
  ],
  // docs: [
  //   {
  //     type: 'category',
  //     label: 'DevOops',
  //     collapsed: false,
  //     items: ['getting-started'],
  //   },
  //   {
  //     type: 'category',
  //     label: 'DevOopsGitReleasePlugin',
  //     collapsed: false,
  //     items: ['gh-release-plugin/config-and-run', 'gh-release-plugin/examples']
  //   },
  //   {
  //     'DevOopsScalaPlugin': ['scala-plugin/how-to-use']
  //   },
  //   {
  //     'DevOopsJavaPlugin': ['java-plugin/how-to-use']
  //   },
  // ],
};
